export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"60eda14c76068b001759f9ac",
				"60eda14c76068b001759f9ae",
				"60edcbd77c5362001af4085a",
				"60ff0ec79eb82b00171f064d",
				"60edab707c5362001af4081a",
				"61177c6f17f5d1001e319b82"
			]
		},
		"60eda14c76068b001759f9ac": {
			"id": "60eda14c76068b001759f9ac",
			"name": "404",
			"pageUrl": "404"
		},
		"60eda14c76068b001759f9ae": {
			"id": "60eda14c76068b001759f9ae",
			"name": "Home",
			"pageUrl": "index",
			"styles": {},
			"customCode": {}
		},
		"60edab707c5362001af4081a": {
			"id": "60edab707c5362001af4081a",
			"pageUrl": "about",
			"name": "About"
		},
		"60edcbd77c5362001af4085a": {
			"id": "60edcbd77c5362001af4085a",
			"pageUrl": "work",
			"name": "Work"
		},
		"60ff0ec79eb82b00171f064d": {
			"id": "60ff0ec79eb82b00171f064d",
			"pageUrl": "uses",
			"name": "Uses"
		},
		"61177c6f17f5d1001e319b82": {
			"id": "61177c6f17f5d1001e319b82",
			"pageUrl": "3d-design",
			"name": "3D Design"
		}
	},
	"mode": "production",
	"projectType": "create-react-app",
	"site": {
		"styles": {
			"height": "",
			"cursor": "url(circle.png), auto",
			"opacity": "",
			"box-shadow": "",
			"border-style": "",
			"border-width": "",
			"background": "#000000",
			"border-radius": "",
			"mix-blend-mode": "overlay",
			"overflow-x": "hidden",
			"overflow-y": "auto",
			"display": "block",
			"transition": "all 0.5s ease 0s",
			"transform": ""
		},
		"seo": {
			"robotsFileType": "autogenerated",
			"sitemapFileType": "custom",
			"og:image": "https://uploads.quarkly.io/60eda14c76068b001759f9a9/images/CR-RF.png?v=2021-07-13T16:03:26.579Z",
			"title": "CreativeRf",
			"og:title": "CreativeRf",
			"hide_for_se": false,
			"favicon_32px": "https://uploads.quarkly.io/60eda14c76068b001759f9a9/images/CR-RF.png?v=2021-07-13T16:03:26.579Z",
			"favicon_apple_152px": "https://uploads.quarkly.io/60eda14c76068b001759f9a9/images/CR-RF.png?v=2021-07-13T16:03:26.579Z",
			"favicon_win10_270px": "https://uploads.quarkly.io/60eda14c76068b001759f9a9/images/CR-RF.png?v=2021-07-13T16:03:26.579Z",
			"background_win10": "#000000",
			"description": "this my portfolio",
			"og:description": "this my portfolio"
		}
	}
}
